<div  class="flash error">
<h1>Acción no encontrada</h1>
<p><strong>Error: </strong>No se encontró la Acción <strong><?= $action?></strong>. Es necesario definir un método en la clase controladora
 <strong><?= $Controller?></strong> llamado <strong><?= $action?></strong> para que esto funcione correctamente.</p>
</div>
<div class="flash valid">
<h1>Solución</h1>
    <h4><strong>Crea el método <em><?= $action?></em> de abajo en la clase <strong><?= $Controller?></strong> del fichero : <br>
    <em class="file"><?= APP_PATH,'controllers/', $controller_path,'_controller.php'?></em></strong></h4>
<pre>
<?php highlight_string("<?php
class {$Controller} extends AppController 
{
    public function {$action}() 
    {
    
    }
	
}") ?>
</pre>
</div>
