<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
	<title>Error - KumbiaPHP Framework</title>
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/kumbia.css" />
</head>
<body>
<header class="row">
    <div class="col-8">
    <h2><?php echo Html::img('logo.png','KumbiaPHP logo') ?>
    <?php echo kumbia_version() ?></h2>
    </div>
</header>
<div class="container">
	<?php echo $content ?>

<h2>Rastro</h2>
<?php foreach ($e->getTrace() as $trace): ?>
    <?php if (isset ( $trace ['file'] ) )//&&
        //!(strpos ( $trace ['file'], APP_PATH) ===false) &&
        //!(strpos ( $trace ['file'], 'index.php')))
    : ?>
        <p><strong><?php echo htmlentities($trace['file'], ENT_NOQUOTES, 'UTF-8') . "(" . $trace ['line'] . ")" ?></strong></p>
            <p>La excepción se ha generado en el archivo <em><?php echo $trace['file'] ?></em> en la línea: <em><?php echo $trace['line'] ?></em>:</p>

        <?php
            $lines = file ( $trace ['file'] );
            $start = ($trace ['line'] - 4) < 0 ? 0 : $trace ['line'] - 4;
            $end = ($trace ['line'] + 2) > count ( $lines ) - 1 ? count ( $lines ) - 1 : $trace ['line'] + 2;
        ?>
        <table>
        <?php for($i = $start; $i <= $end; $i ++): ?>
        <tr <?php if ($i == $trace ['line'] - 1): ?> style="background:#ff0" <?php endif; ?>>
            <th><?php echo ($i + 1) ?></th>
            <td><?php echo str_replace('&lt;?php', '', highlight_string('<?php '.$lines[$i], true)) ?></td>
        </tr>
        <?php endfor; ?>
        </table>

        <?php endif; ?>
    <?php endforeach; ?>

    <table class="t">
        <thead>
            <tr>
            <th>#</th>
            <th>Fichero (línea)</th>
            <th>Función</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $lines = explode("\n",$e->getTraceAsString());
	   $files = get_included_files();
	   foreach ($lines as $line){
	       $line = explode(" ",$line);
        ?>
	    <tr>
            <td><?php echo $line[0] ?></td>
            <td><?php echo $line[1] ?></td>
            <td><?php if(isset($line[2])) echo $line[2] ?></td>
        </tr>
	 <?php } ?>
	</tbody>
    </table>

<h2>Información Adicional</h2>
<div class="col-6">
    <strong>En producción:</strong> <?php echo PRODUCTION ?  'Sí' : 'No' ?><br />
    <strong>Ubicación actual:</strong> <?php echo $route ?><br />
    <strong>Librerías:</strong> <?php //echo $boot['modules']['libs'] ?><br />
    <strong>Server: </strong> <?php echo $_SERVER['SERVER_SOFTWARE'] ?><br />
</div>

<div class="col-6">
    <strong>IP Server: </strong> <?php echo $_SERVER['SERVER_ADDR'] ?><br />
    <strong>IP Visitante: </strong> <?php echo $_SERVER['REMOTE_ADDR'] ?><br />
    <strong>Archivos incluidos: </strong> <?php echo count($files) ?>
</div> 

</div>
<?php include APP_PATH.'views/_shared/partials/kumbia/footer.phtml' ?>
</body>
</html>
