<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="<?= APP_CHARSET ?>" />
    <title>Oh! Hay un error - KumbiaPHP Framework</title>
    <style>
    * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    }
    html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}
    body{margin:0}
    a{color:#0ac;font-weight:bold;text-decoration:none}
    a:hover,a:focus{color:#ff4d4d;text-decoration:underline}
    a:focus{outline:thin dotted #333;outline:5px auto -webkit-focus-ring-color;outline-offset:-2px}
    ul.inline {padding-left: 0px;list-style: outside none none}
    ul.inline > li {display: inline-block;padding-left: 5px;padding-right: 5px;}
    
    /* Formatea los mensajes Flash::xxx() de KumbiaPHP */
    .flash {
        margin: 5px 0;
        min-height: 32px;
        padding:3px 10px 3px 50px;
        background-repeat: no-repeat;
        background-position: 10px center;
        line-height: 32px;
        border-radius: 2px;
    }

    .error {
        color: #D8000C;
        background-color: #FFBABA;
    }

    .info {
        color: #00529B;
        background-color: #BDE5F8;
    }

    .valid {
        color: #4F8A10;
        background-color: #DFF2BF;
    }
    .warning {
        color: #9F6000;
        background-color: #FEEFB3;
    }
    pre{display:block;padding:10.5px;margin:0 0 11px;line-height:1.5;word-break:break-all;word-wrap:break-word;color:#333;background-color:#f5f5f5;border-radius: 5px;}
    pre code{padding:0;font-size:inherit;color:inherit;white-space:pre-wrap;border:0}
    
    .container{margin-right:auto;margin-left:auto;padding-left:15px;padding-right:15px}
    .container:before,.container:after{content:" ";display:table;}
    .container:after{clear:both}
    .col-6{width:50%;float:left}
    
    #trace{background-color:#DDD;padding:2em;margin-bottom:1.5em}
    #trace table {background-color:white;width:100%}
    
    .file{word-break: break-word;}
    .php {width: 100%;border-spacing: 2px 2px;color: white;margin:1em 0;table-layout: fixed}
    .php td{background-color:#00A1CB; text-align:center;padding-bottom:.5em}
    .php tr:nth-child(even) td{background-color:#007493}
    .php a{color:#FFF}
    
    #files li[title ^='<?= CORE_PATH?>']{color: red;}
    #files li[title ^='<?= APP_PATH?>']{color: green;}
    #files li[title ^='<?= dirname(CORE_PATH).'/vendor/'?>']{color: #ffcc00;}
    
    .status{padding:5px;border-radius:5px;margin-left:5px;color:#FFF}
    .status.red{background-color:#a33}
    .status.green{background-color:#759e1a}
    .status.blue{background-color:#0A29FF}
    
    #viewfiles{display:none}
    #viewfiles:target{display:block}
    
    table.t{margin:auto;margin-bottom:22px;width:100%}
    table.t tr>th,table.t tr>td{padding:8px;line-height:1.5;border-top:1px solid #ddd}
    table.t thead>tr>th{vertical-align:bottom;border-bottom:2px solid #ddd}
    table.t tbody tr:hover{background-color:#BDE5F8}
       
    footer{border-top:4px solid #00A1CB;margin-top:-5px;padding:1em}
    </style>
</head>
<body>
<div class="">
<header class="row">
    <h2><?= Html::img('logo.png','KumbiaPHP logo')//TODO: embed png data: ?>
    <?= kumbia_version() ?></h2>
</header>

	<?= $content ?> 

</div>
<div id="trace">
<h1>Rastro</h1>
<?php foreach ($e->getTrace() as $trace): ?>
    <?php if (isset ( $trace ['file'] ) )//&&
        //!(strpos ( $trace ['file'], APP_PATH) ===false) &&
        //!(strpos ( $trace ['file'], 'index.php')))
    : ?>
        <p><strong class="file"><?= htmlentities($trace['file'], ENT_NOQUOTES, 'UTF-8') . "(" . $trace ['line'] . ")" ?></strong></p>
        <!-- <p>La excepción se ha generado en el archivo <em class="file"><?= $trace['file'] ?></em> en la línea: <em><?= $trace['line'] ?></em>:</p> -->

        <?php
            $lines = file ( $trace ['file'] );
            $start = ($trace ['line'] - 4) < 0 ? 0 : $trace ['line'] - 4;
            $end = ($trace ['line'] + 2) > count ( $lines ) - 1 ? count ( $lines ) - 1 : $trace ['line'] + 2;
        ?>
        <table>
        <?php for($i = $start; $i <= $end; $i ++): ?>
        <tr <?php if ($i == $trace ['line'] - 1): ?> style="background:#BDE5F8" <?php endif; ?>>
            <th><?= ($i + 1) ?></th>
            <td><?= str_replace('&lt;?php', '', highlight_string('<?php '.$lines[$i], true)) ?></td>
        </tr>
        <?php endfor ?>
        </table>

    <?php endif ?>
<?php endforeach ?> 
</div>
    <table class="t">
        <thead>
            <tr>
            <th>#</th>
            <th>Fichero (línea)</th>
            <th>Función</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $lines = explode("\n",$e->getTraceAsString());
	   $files = get_included_files();
	   foreach ($lines as $line){
	       $line = explode(" ",$line);
        ?>
	    <tr>
            <td><?= $line[0] ?></td>
            <td><?= $line[1] ?></td>
            <td><?php if(isset($line[2])) echo $line[2] ?></td>
        </tr>
	 <?php } ?>
	</tbody>
    </table>

<h2>Información Adicional</h2>
<div class="container">
<div class="col-6">
    <strong>Ubicación actual:</strong> <?= $route ?><br />
</div>

<div class="col-6">
    <strong>IP Visitante: </strong> <?= $_SERVER['REMOTE_ADDR'] ?><br />
</div>
</div></div>

<div class="view">


</div>

<div id="viewfiles">
<ol id="files"><!-- TODO: usar :hover para mostrarlos -->
<?php 
foreach($files as $file) : ?>
    <li title="<?= $file ?>"><?= $file ?></li>
<?php endforeach ?> 
</ol>
<span class="status red">core</span>
<span class="status green">app</span>
<span class="status blue">vendor</span>
</div>

<table class="php"><tr>
<td><h3><?= round((microtime(1)-START_TIME),4),' seg.'?></h3>Tiempo</td><td><h3><?= number_format(memory_get_usage() / 1048576, 2),' MB';?></h3>Memoria Usada</td><td><h3><span class="status <?= extension_loaded('xdebug') ? 'green' : 'red' ?>" title="Recomendable en desarrollo. Nunca en producción">xdebug</span><span class="status <?= extension_loaded('apc') ? 'green' : 'red'; ?>" title="Siempre muy recomendable">apc</span></h3>PHP extensions</td><td><h3><a href="#viewfiles"><?= count($files) ?> ficheros</a></h3>Includes</td>
</tr>
<tr>
<td><h3><?= ini_get('max_execution_time'),' seg.'?></h3>Tiempo Máximo PHP</td><td><h3><?= ini_get('memory_limit') ?></h3>Memoria PHP</td><td><h3><?= PHP_VERSION?><br><small title="PHP SAPI"><?= PHP_SAPI ?></small></h3>Versión PHP</td><td><h3><?= $_SERVER['SERVER_SOFTWARE'] ?> <br><small>IP: </strong> <?= $_SERVER['SERVER_ADDR'] ?></small></h3>Servidor</td>
</tr>
</table>

<div class="flash info">
<p>En <b>PRODUCCIÓN</b> no sale este error, muestra el template de error de la app: <br>
<em class="file"><?= APP_PATH ?>views/_shared/errors/404.phtml</em> <br>
¡ Modifica el template de error 404 a tu gusto !</p>
</div>
 
<footer>
    <div class="col-6">
        <ul class="inline">
        	<li><a href="http://www.kumbiaphp.com/">KumbiaPHP Framework</a> |</li>
        	<li><a href="http://wiki.kumbiaphp.com/">Wiki</a> |</li>
        	<li><a href="https://docs.google.com/document/d/1kth1GhrmMEBK2cAMyiy_4Dw1qlJFNdXVuXajJ6nMTQg/edit?hl=es">Manual</a> |</li>
        	<li><a href="http://wiki.kumbiaphp.com/Licencia" title="New BSD">Licencia</a></li>
        </ul>
        <div>
            <a href="http://wiki.kumbiaphp.com/Team_Development_KumbiaPHP_Framework">© 2007 - 2015 KumbiaPHP Team</a>
        </div>
    </div>
    <div class="col-6">
        <p>Ayuda Online: <a href="irc://irc.freenode.org/#kumbiaphp" title="IRC donde podrás encontrar ayuda a problemas que tengas, hacer comentarios, proponer ideas, reportar bugs, socializar temas relacionados y disfrutar de KumbiaPHP.">IRC</a> | 
        				 <a href="http://webchat.freenode.net/?channels=kumbiaphp" title="Web Chat IRC donde podrás encontrar ayuda a problemas que tengas, hacer comentarios, proponer ideas, reportar bugs, socializar temas relacionados y disfrutar de KumbiaPHP.">Web IRC</a> | 
        				 <a href="http://groups.google.com/group/kumbia" title="Lista de Correo de KumbiaPHP donde podrás encontrar ayuda a problemas que tengas, hacer comentarios, proponer ideas, reportar bugs, socializar temas relacionados y disfrutar de KumbiaPHP.">Grupo</a> | <a href="http://foro.kumbiaphp.com" title="Foro de KumbiaPHP donde podrás encontrar ayuda a problemas que tengas, hacer comentarios, proponer ideas, reportar bugs, socializar temas relacionados y disfrutar de KumbiaPHP.">Foro</a></p>
    </div>
    
    <p>Ejecutado en <?= round((microtime(1)-START_TIME),4),' seg.'?> usando <?= number_format(memory_get_usage() / 1048576, 2),' MB' ?> de memoria</p>
</footer>
</body>
</html>
