<div id='logo-kumbia'><?php echo img_tag('default/kumbia.png') ?></div>
    <div id='info'>
        <h1>Bienvenido a KumbiaPHP Framework</h1>
        <p>Ya puedes empezar a usar el mejor framework para desarrollar aplicaciones web con PHP.</p>
        <p>Kumbia es un web framework libre escrito en PHP5. Basado en las mejores prácticas
            de desarrollo web, usado en software comercial y educativo, Kumbia fomenta la velocidad   
            y eficiencia en la creación y mantenimiento de aplicaciones web, reemplazando táreas de
            codificación repetitivas por poder, control y placer.</p>   
        <p>Si ha visto a Ruby-Rails/Python-Django encontrará a Kumbia una alternativa para proyectos en PHP con caracterásticas como:</p>
        <ul>
            <li>Sistema de Plantillas sencillo</li>
            <li>Administración de Cache</li>
            <li>Scaffolding Avanzado</li>
            <li>Programación Modular</li>
            <li>Modelo de Objetos y Separación MVC</li>
            <li>Soporte para AJAX</li>
            <li>Componentes Gráficos</li>
            <li>Seguridad</li>
        </ul>
        <p>y muchas cosas más. Kumbia puede ser la solución que esta buscando. </p>
    </div>