<div id='info'>
<?php
    echo strftime("%e de %B del %Y")."<br />";
    
    /**
     * Verificando permisos del dir temp/
     */
    if(!is_writable(APP_PATH.'temp')){
        $tmp = "Debes darle permiso a: '".basename(APP_PATH)."/temp/'";
    } else {
        $tmp = 'Directorio temp... ok';
    }
    
    /**
     * Configuracion del config.ini
     */
    $config = Config::read('config');
    
    $databases = ($config['application']['database']) ? 'On' : 'Off';
    $models_autoload = ($config['application']['models_autoload']) ? 'On' : 'Off';
    $status = ($config['application']['production']) ? 'Production' : 'Development';
    
    if(isset($config['application']['locale'])){
        $locale = $config['application']['locale'];
    } else {
        $locale = 'No se ha especificado un locale';
    }
    if(isset($config['application']['timezone'])){
        $timezone = $config['application']['timezone'];
    } else {
        $timezone = 'No se ha especificado un Timezone en el config.ini. Pero el servidor tiene <strong>'.date_default_timezone_get().'</strong>';
    }
    if(isset($config['application']['cache_driver'])){
        $cahe_driver = $config['application']['cache_driver'];
    } else {
        $cache_driver = 'No ha seleccionado un driver para la cache';
    }
    
?>
        <span class='title'>config.ini </spam><spam class='app'> de <?php echo APP ?></span>
 
         <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Directorio temp/</strong>:</div>
                    <div class="field-widget"><?php echo $tmp ?></div>
                </div>
            </div>
        </div>

        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Estado Actual del Framework</strong>: <?php echo $status ?></div>
                    <div class="field-widget">Ver <a href='http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#Modos_de_una_Aplicaci.C3.B3n'>Modos de ejecución</a></div>
                </div>
            </div>
        </div>
        
        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Carga Automática de Modelos</strong>: <?php echo $databases?></div>
                    <div class="field-widget">Habilita la carga de modelos automática.</div>
                </div>
            </div>
        </div>
        
        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Base de Datos</strong>: <?php echo $config['application']['database'] ?></div>
                    <div class="field-widget">Datos de la conexión a la BD que será utilizada, ver configuración <a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">databases.ini</a>.</div>
                </div>
            </div>
        </div>
        
        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Autocarga de Modelos</strong>: <?php echo $models_autoload ?></div>
                    <div class="field-widget">Ver <a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#Carga_selectiva_de_modelos">Carga Selectiva de Modelos</a>.</div>
                </div>
            </div>
        </div>

        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Charset</strong>: <?php echo $config['application']['charset'] ?></div>
                    <div class="field-widget">Codificación de caracteres. Recomendado UTF-8</div>
                </div>
            </div>
        </div>
        
        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>TimeZone</strong>: <?php echo $timezone ?></div>
                    <div class="field-widget">Zona horaria que usará el Framework.</div>
                </div>
            </div>
        </div>

        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Cache Driver</strong>: <?php echo $cahe_driver ?></div>
                    <div class="field-widget">Driver que se utilizara para realizar las operaciones de cache.</div>
                </div>
            </div>
        </div>
        
        <div class="x-form-item">
            <div class='rows-left'>
                <div class="form-row">
                    <div class="field-label"><strong>Locale</strong>: <?php echo $locale ?></div>
                    <div class="field-widget">Localización. Característica que depende de los locale instalado en el servidor.</div>
                </div>
            </div>
        </div>
        
</div>
