<?php
/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://wiki.kumbiaphp.com/Licencia
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@kumbiaphp.com so we can send you a copy immediately.
 *
 * Vista parcial para cargar jsCalendar
 * 
 * @category   Kumbia
 * @package    Partials 
 * @copyright  Copyright (c) 2005-2009 Kumbia Team (http://www.kumbiaphp.com)
 * @license    http://wiki.kumbiaphp.com/Licencia     New BSD License
 */

if(!isset($language)) {
    $language = 'calendar-es';
}

if(!isset($theme)) {
    $theme = 'theme-1';
}
?>

<link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>css/style-calendar/<?php echo $theme ?>.css"/>

<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>javascript/kumbia/jscalendar/calendar.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>javascript/kumbia/jscalendar/calendar-setup.js"></script>
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>javascript/kumbia/jscalendar/<?php echo $language ?>.js"></script>