<div id="contenido">
	<?php echo img_tag('site_logo.gif','id: logo','alt: KumbiaPHP') ?> 
	<h1 id="version">VERSI&Oacute;N <?php echo Kumbia::KUMBIA_VERSION?> </h1>
         
	<div id="info">
		<h1>Bienvenido a Kumbia PHP Framework</h1>
		<p>Ya puedes empezar a usar el mejor framework para desarrollar aplicaciones web con PHP.</p>
		<p>Kumbia es un web framework libre escrito en PHP5. Basado en las mejores pr&aacute;cticas
		de desarrollo web, usado en software comercial y educativo, Kumbia fomenta la velocidad   
		y eficiencia en la creaci&oacute;n y mantenimiento de aplicaciones web, reemplazando t&aacute;reas de
		codificaci&oacute;n repetitivas por poder, control y placer.</p>   
		<p>Si ha visto a Ruby-Rails/Python-Django encontrar&aacute; a Kumbia una alternativa para proyectos en PHP con caracter&iacute;sticas como:</p>
		<ul>
			<li>Sistema de Plantillas sencillo</li>
			<li>Administraci&oacute;n de Cache</li>
			<li>Scaffolding Avanzado</li>
			<li>Programaci&oacute;n Modular</li>
			<li>Modelo de Objetos y Separaci&oacute;n MVC</li>
			<li>Soporte para AJAX</li>
			<li>Generaci&oacute;n de Formularios</li>
			<li>Componentes Gr&aacute;ficos</li>
			<li>Seguridad</li>
		</ul>
		<p>y muchas cosas m&aacute;s. Kumbia puede ser la soluci&oacute;n que esta buscando. </p>
	</div>
	<div id="footer">
		<ul class="links">
			<li><a href='http://www.kumbiaphp.com/blog/'>Web</a> |</li>
			<li><a href='http://www.kumbiaphp.com/foro/'>Foro</a> |</li>
			<li><a href='http://groups.google.com/group/kumbia'>Grupo</a> |</li>
			<li><a href='http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt'>Licencia GPL</a></li>
		</ul>
	</div>
</div>