<div id='logo-kumbia'><?php echo Html::img('default/kumbia.png','KumbiaPHP logo') ?></div>
    <div id='info'>
		<h1>KumbiaPHP está listo para usarse</h1>
        <p><strong>Bienvenido a KumbiaPHP Framework</strong>. El framework ya está listo para desarrollar aplicaciones web con PHP de la manera más fácil
       posible, sin tener que reinventar la rueda, y preocupandose por lo más importante, la lógica de su aplicación.</p>
        <h2>¿Que es KumbiaPHP?</h2>
        <p>Kumbia es un web framework libre escrito en PHP5. Basado en las mejores prácticas
            de desarrollo web, usado en software comercial y educativo, Kumbia fomenta la velocidad
            y eficiencia en la creación y mantenimiento de aplicaciones web, reemplazando táreas de
            codificación repetitivas por poder, control y placer.</p>
        <p>Si ha visto a Ruby-Rails/Python-Django encontrará a Kumbia una alternativa para proyectos en PHP con caracterásticas como:</p>
        <ul>
            <li>Sistema de Plantillas sencillo</li>
            <li>Administración de Cache</li>
            <li>Scaffolding Avanzado</li>
            <li>Programación Modular</li>
            <li>Modelo de Objetos y Separación MVC</li>
            <li>Soporte para AJAX</li>
            <li>Componentes Gráficos</li>
            <li>Seguridad</li>
        </ul>
        <p>y muchas cosas más. Kumbia puede ser la solución que esta buscando. </p>
        <h2>Documentación</h2>
        <p>En nuestra wiki podrás encontrar información actualizada sobre el uso del framework, tal vez te interese saber sobre:
		<ul>
			<li><a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Primera aplicación en KumbiaPHP(Hola Mundo)</a></li>
			<li><a href="http://wiki.kumbiaphp.com/Como_hacer_un_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a></li>
			<li><a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a></li>

		</ul>
		Estos son solo algunos ejemplos puedes ver más en la <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a>
        </p>
    </div>
