    <div class="hero">
		<h2>KumbiaPHP <?= kumbia_version() ?> está listo para usarse</h2>
        <h3>Bienvenido a KumbiaPHP Framework</h3>
        <p>El framework ya está listo para desarrollar aplicaciones web con PHP, rápida y fácilmente, sin tener que reinventar la rueda, y preocupándose por lo más importante, la lógica de su aplicación.</p>
       <?= Html::link('pages/kumbia/status/', 'Ver Config', 'title="Ver configuración de la aplicación" class="btn btn-info"') ?>
    </div>
    <h2>Cómo empezar</h2>
    <p>En nuestra <a href="http://wiki.kumbiaphp.com/">wiki</a> podrás encontrar información actualizada sobre el uso del framework,
    si estas comenzando con <em>KumbiaPHP</em> deberías realizar  la
    <strong><a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Aplicación Hola Mundo</a></strong>.</p>
    <p>También puede interesarte saber sobre:</p>
	<ul>
		<li><a href="http://wiki.kumbiaphp.com/V1.0_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a></h3></li>
		<li><a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a></li>
		<li><a href="https://github.com/KumbiaPHP/Documentation/blob/master/es/active-record.md#configurando-conexi%C3%B3n-a-la-base-de-datos">Configurar conexiones a bases de datos</a></li>
	</ul>
	<p>Estos son sólo algunos ejemplos, puedes ver más en la <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a></p>    
