<div style="text-align: center; margin: 50px; font-size: 12pt; background-color: transparent; font-family: Lucida Grande, Verdana, Sans-serif;">
	<table align="center" id="content" style="background-color: #fff; border: #999 1px solid; padding: 10px 10px 6px 10px; width: 50%;">
		<tbody>
			<tr>
				<td style="width: 5%">
					<img src="<?php echo PUBLIC_PATH ?>img/site_logo.gif" />
				</td>
				<td>
					<h1 style="font-size: 14pt; color: #990000; margin: 0 0 4px 0;">ERROR 404</h1>
				</td>
			</tr>
		</tbody>
	</table>
</div>