<?php
/* datos a formatear*/
$data = (array) $data;

if(isset($filename)) {
    header("Content-Disposition: attachment; filename=\"$filename.csv\"");
}
/*mime type para el contenido*/
header("Content-type: text/csv");
/*apertura del buffer de salida*/
$buffer = fopen('php://output', 'w');
foreach ($data as $line) {
    fputcsv($buffer, is_object($line) ? get_object_vars($line) : $line, $delimiter ?? ',');
}
fclose($buffer);
