<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>KumbiaPHP Framework</title>
  <?php Tag::css('kumbia') ?>
  <?= Html::includeCss() ?>
</head>
<body>
<header class="row">
    <div class="col-8">
    <h2><?= Html::img('logo.png','KumbiaPHP logo') ?>
    <?= kumbia_version() ?></h2>
    </div>
    <div class="col-4">
        Entorno:  <strong><?= basename(dirname(APP_PATH)) ?></strong>
    </div>
</header>
<div class="container"><?php View::content() ?></div>
<?php View::partial('kumbia/footer') ?>
</body>
</html>
