<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>KumbiaPHP Framework</title>
  <?php Tag::css('kumbia') ?>
  <?= Html::includeCss() ?>
</head>
<body>
<div class="container">
  <header class="row">
      <div class="col-8">
        <?= Html::img('kumbiaphp.svg','KumbiaPHP logo') ?>
      </div>
      <div class="col-4 text-right">
          Entorno:  <strong><?= basename(dirname(APP_PATH)) ?></strong>
      </div>
  </header>
  <?php View::content() ?>
  <?php View::partial('kumbia/footer') ?>
</div>
</body>
</html>
