<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>KumbiaPHP web &amp; app Framework</title>
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css" />
</head>
<body>
    <div style="text-align: center; margin: 50px; font-size: 12pt; background-color: transparent; font-family: Lucida Grande, Verdana, Sans-serif;">
        <table align="center" id="content" style="background-color: #fff; border: #999 1px solid; padding: 10px 10px 6px 10px; width: 50%;">
            <tbody>
                <tr>
                    <td style="width: 5%">
                        <a href="http://www.kumbiaphp.com"><img src="<?php echo PUBLIC_PATH ?>img/site_logo.gif" alt="Kumbia PHP Framework"/></a>
                    </td>
                    <td>
                        <h1 style="font-size: 14pt; color: #990000; margin: 0 0 4px 0;">ERROR 404</h1>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>
