<div id="footer">
    <div class='alignleft'>
        <ul class="links" >
        	<li><a href='http://www.kumbiaphp.com/'>KumbiaPHP Framework</a> |</li>
        	<li><a href='http://wiki.kumbiaphp.com/'>Wiki</a> |</li>
        	<li><a href='http://ufpr.dl.sourceforge.net/sourceforge/kumbia/Manual_Kumbia_PHP_Framework_v0-5.pdf'>Manual PDF</a> |</li>
        	<li><a href='http://wiki.kumbiaphp.com/Indice'>Manual Online</a> |</li>
        	<li><a href='http://wiki.kumbiaphp.com/Licencia' title='New BSD'>Licencia</a></li>
        </ul>
    </div>
    <div class='alignright'>
        <p>Ayuda Online: <a href='irc://andromeda.irc-hispano.org/#kumbia'>IRC</a> | <a href='http://groups.google.com/group/kumbia'>Grupo</a></p>
    </div>
    <div class='alignleft clear'><a href='http://wiki.kumbiaphp.com/Team_Development_KumbiaPHP_Framework'>© 2009 KumbiaPHP Team</a></div>
    <div class='alignright'><p><?php echo 'Tiempo: '.round((microtime(1)-START_TIME),4).' seg.'; echo ', Memoria Usada: '.number_format(memory_get_usage() / 1048576, 2).' MB';?></p></div>
</div>
