<?php
/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://wiki.kumbiaphp.com/Licencia
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@kumbiaphp.com so we can send you a copy immediately.
 *
 * Esta es la clase principal del framework, contiene metodos importantes
 * para cargar los controladores y ejecutar las acciones en estos ademas
 * de otras funciones importantes
 * 
 * @category   Kumbia
 * @package    Partials 
 * @copyright  Copyright (c) 2005-2009 Kumbia Team (http://www.kumbiaphp.com)
 * @license    http://wiki.kumbiaphp.com/Licencia     New BSD License
 */

extract(Router::get(), EXTR_OVERWRITE);
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/scriptaculous/prototype.js'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/scriptaculous/effects.js'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/scriptaculous/dragdrop.js'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/kumbia/base.js'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/kumbia/validations.js'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/kumbia/main.php?module=$module&amp;path=" . urlencode(PUBLIC_PATH) . "&amp;controller=$controller&amp;action=$action&amp;id=$id'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/kumbia/swfobject.js'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/scriptaculous/unittest.js'></script>"; 
echo "<script type='text/javascript' src='", PUBLIC_PATH, "javascript/scriptaculous/scriptaculous.js'></script>";